/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_database;

import javax.swing.Action;
import javax.swing.table.DefaultTableModel;

 
/**
 *
 * @author mathu
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmployeeButtonGroup = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FTEtable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        PTEtable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        FName = new javax.swing.JTextField();
        LName = new javax.swing.JTextField();
        WorkLocaText = new javax.swing.JTextField();
        DeductionText = new javax.swing.JTextField();
        FTEbutton = new javax.swing.JRadioButton();
        PTEbutton = new javax.swing.JRadioButton();
        ASalTextF = new javax.swing.JTextField();
        WperYText = new javax.swing.JTextField();
        HperWText = new javax.swing.JTextField();
        HWageText = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        eNumFTxt = new javax.swing.JFormattedTextField();
        Sex = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FTEtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Sex", "Work Location", "Deductions", "Annual salary"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FTEtable);

        PTEtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "First Name", "Last Name", "Sex", "Work Location", "Deductions", "Hourly wage", "Hours per Week", "Weeks per Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(PTEtable);

        jLabel1.setText("Full Time Employees");

        jLabel2.setText("Part Time Employees");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
            .addComponent(jScrollPane3)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Archive", jPanel2);

        FName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FName.setText("First Name");
        FName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FNameActionPerformed(evt);
            }
        });

        LName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        LName.setText("Last Name");
        LName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LNameActionPerformed(evt);
            }
        });

        WorkLocaText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        WorkLocaText.setText("Work Location");
        WorkLocaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WorkLocaTextActionPerformed(evt);
            }
        });

        DeductionText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        DeductionText.setText("Deductions");
        DeductionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeductionTextActionPerformed(evt);
            }
        });

        EmployeeButtonGroup.add(FTEbutton);
        FTEbutton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        FTEbutton.setText("Full Time Employee");
        FTEbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FTEbuttonMouseClicked(evt);
            }
        });

        EmployeeButtonGroup.add(PTEbutton);
        PTEbutton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        PTEbutton.setText("Part Time Employee");
        PTEbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PTEbuttonMouseClicked(evt);
            }
        });

        ASalTextF.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ASalTextF.setText("Annual Salary");
        ASalTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASalTextFActionPerformed(evt);
            }
        });

        WperYText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        WperYText.setText("Weeks per Year");
        WperYText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WperYTextActionPerformed(evt);
            }
        });

        HperWText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HperWText.setText("Hours per Week");
        HperWText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HperWTextActionPerformed(evt);
            }
        });

        HWageText.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        HWageText.setText("Hourly Wage");
        HWageText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HWageTextActionPerformed(evt);
            }
        });

        AddButton.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        AddButton.setText("Add");
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AddButtonMousePressed(evt);
            }
        });

        eNumFTxt.setText("Employee Number");
        eNumFTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        eNumFTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eNumFTxtActionPerformed(evt);
            }
        });

        Sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(AddButton)
                                .addGap(287, 287, 287))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eNumFTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                                    .addComponent(FName))
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(DeductionText, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                            .addComponent(LName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PTEbutton)
                                    .addComponent(FTEbutton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(WperYText)
                                    .addComponent(ASalTextF, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(HperWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(HWageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(WorkLocaText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 238, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sex, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeductionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNumFTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(WorkLocaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FTEbutton)
                    .addComponent(ASalTextF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PTEbutton)
                    .addComponent(WperYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HperWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HWageText, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FNameActionPerformed

    private void LNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LNameActionPerformed

    private void WorkLocaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WorkLocaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WorkLocaTextActionPerformed

    private void DeductionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeductionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeductionTextActionPerformed

    private void PTEbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PTEbuttonMouseClicked
        // TODO add your handling code here:
        ASalTextF.setEnabled(false);
        HWageText.setEnabled(true);
        HperWText.setEnabled(true);
        WperYText.setEnabled(true);
    }//GEN-LAST:event_PTEbuttonMouseClicked

    private void FTEbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FTEbuttonMouseClicked
        // TODO add your handling code here:
        ASalTextF.setEnabled(true);
        HWageText.setEnabled(false);
        HperWText.setEnabled(false);
        WperYText.setEnabled(false);
    }//GEN-LAST:event_FTEbuttonMouseClicked

    private void AddButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMousePressed
        // TODO add your handling code here:
                MyHashTable Hash = new MyHashTable(20);


        if( AddButton.isEnabled() == true){
            int eNum = Integer.parseInt(eNumFTxt.getText());
            int workLocaTxt = Integer.parseInt(WorkLocaText.getText());
            double deduc = Double.parseDouble(DeductionText.getText());
            if (PTEbutton.isSelected() == true){
                System.out.println("PTE");

                int HperW = Integer.parseInt(HperWText.getText());
                int WperY = Integer.parseInt(WperYText.getText());
                double wage = Double.parseDouble(HWageText.getText());
            
                PartTimeEmployee PTE = new PartTimeEmployee(eNum,FName.getText(), LName.getText(),workLocaTxt,deduc,Sex.getName(),HperW, WperY, wage);
                Hash.addEmployee(PTE); 
                
                DefaultTableModel model = (DefaultTableModel) PTEtable.getModel();
                model.addRow(new Object[]{FName.getText(), LName.getText(),Sex.getName(),workLocaTxt,deduc,HperW, WperY, wage});
                
            }else if (FTEbutton.isSelected() == true){
               System.out.println("FTE");

                double aSal = Double.parseDouble(ASalTextF.getText());
                
                FullTimeEmployee FTE = new FullTimeEmployee(eNum,FName.getText(), LName.getText(),workLocaTxt,deduc,Sex.getName(),aSal);
                Hash.addEmployee(FTE);
                
                DefaultTableModel model = (DefaultTableModel) FTEtable.getModel();
                model.addRow(new Object[]{FName.getText(), LName.getText(),Sex.getName(),workLocaTxt,deduc,aSal});
            } else {
            }
            
            System.out.println("button pressed");
        }
    }//GEN-LAST:event_AddButtonMousePressed

    private void ASalTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASalTextFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ASalTextFActionPerformed

    private void HWageTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HWageTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HWageTextActionPerformed

    private void WperYTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WperYTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WperYTextActionPerformed

    private void HperWTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HperWTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HperWTextActionPerformed

    private void eNumFTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eNumFTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eNumFTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
                
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ASalTextF;
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField DeductionText;
    private javax.swing.ButtonGroup EmployeeButtonGroup;
    private javax.swing.JTextField FName;
    private javax.swing.JRadioButton FTEbutton;
    private javax.swing.JTable FTEtable;
    private javax.swing.JTextField HWageText;
    private javax.swing.JTextField HperWText;
    private javax.swing.JTextField LName;
    private javax.swing.JRadioButton PTEbutton;
    private javax.swing.JTable PTEtable;
    private javax.swing.JComboBox<String> Sex;
    private javax.swing.JTextField WorkLocaText;
    private javax.swing.JTextField WperYText;
    private javax.swing.JFormattedTextField eNumFTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
